version: '3.7'

services:
  hack_db:
    image: postgres:latest
    container_name: hack_db
    ports:
      - "1337:5432"
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: backend
    command: bash -c "alembic upgrade head && cd src && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - hack_db
