"""champion nullable

Revision ID: b3b26c88b0ea
Revises: ae775e0e1efe
Create Date: 2024-10-26 22:54:57.070938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b26c88b0ea'
down_revision: Union[str, None] = 'ae775e0e1efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season', 'champion_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season', 'champion_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
